# version: "3.8"
# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: password
#     restart: unless-stopped
#   backend:
#     build: "./backend"
#     container_name: backend_api
#     env_file: ./backend/.env
#     depends_on:
#       - mongodb
#     ports:
#       - "5000:5000"
#   frontend:
#     build: ./frontend
#     container_name: frontend-react
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     environment:
#       - NEXT_PUBLIC_API_URL=
# volumes:
#   mongodb_data:
#     driver: local
# name: "mern-app"
# services:
#   mongo:
#     image: mongo:7
#     port:
#       - 27017:27017
#     volumes:
#       - mongodb_data:/data/db
#     networks:
#       - mern-app
#   api:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     env_file: ./backend/.env
#     networks:
#       - mern-app
#     ports:
#       - 5000:5000

# volumes:
#   mongodb_data:
# networks:
#   mern-app:
#     driver: bridge
# version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-app
    env_file: ./frontend/.env
    stdin_open: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      - mongo
    env_file: ./backend/.env
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=badhon
networks:
  mern-app:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
